//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALTiger
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExistenciaProducto
    {
        public int productoID { get; set; }
        public Nullable<int> MaximoProducto { get; set; }
        public Nullable<int> Existensia { get; set; }
        public Nullable<int> MinimoProducto { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public Nullable<System.DateTime> Changed { get; set; }
        public Nullable<int> ChangedBy { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
