//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALTiger
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int Id { get; set; }
        public Nullable<int> ProvedorID { get; set; }
        public Nullable<int> FotoID { get; set; }
        public string ProductName { get; set; }
        public string ProductDetails { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<decimal> PrecioDescuento { get; set; }
        public Nullable<decimal> Lista { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public Nullable<System.DateTime> Changed { get; set; }
        public Nullable<int> ChangedBy { get; set; }
        public int MarcaId { get; set; }
        public int VehiculoId { get; set; }
    
        public virtual ExistenciaProducto ExistenciaProducto { get; set; }
        public virtual Foto Foto { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
