//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALTiger
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarjetaCredito
    {
        public int Id { get; set; }
        public Nullable<int> PersonID { get; set; }
        public Nullable<int> DireccionID { get; set; }
        public string NombreTarjeta { get; set; }
        public string Descripcion { get; set; }
        public string Numero { get; set; }
        public string NumeroDeSuguridad { get; set; }
        public Nullable<System.DateTime> FechaCaducidad { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public Nullable<System.DateTime> Changed { get; set; }
        public Nullable<int> ChangedBy { get; set; }
    }
}
