//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALTiger
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrompEntities : DbContext
    {
        public PrompEntities()
            : base("name=PrompEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cancelacione> Cancelaciones { get; set; }
        public virtual DbSet<ClienteEntrega> ClienteEntregas { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<CuentaVendedor> CuentaVendedors { get; set; }
        public virtual DbSet<Direccion> Direccions { get; set; }
        public virtual DbSet<Email> Emails { get; set; }
        public virtual DbSet<ExistenciaProducto> ExistenciaProductoes { get; set; }
        public virtual DbSet<Foto> Fotoes { get; set; }
        public virtual DbSet<Marca> Marcas { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<PreguntaSeguridad> PreguntaSeguridads { get; set; }
        public virtual DbSet<Producto> Productoes { get; set; }
        public virtual DbSet<ProveedorEnvio> ProveedorEnvios { get; set; }
        public virtual DbSet<Proveedor> Proveedors { get; set; }
        public virtual DbSet<RazonCancelacion> RazonCancelacions { get; set; }
        public virtual DbSet<RespuestaPreguntaSeguridad> RespuestaPreguntaSeguridads { get; set; }
        public virtual DbSet<TarjetaCredito> TarjetaCreditoes { get; set; }
        public virtual DbSet<Telefono> Telefonos { get; set; }
        public virtual DbSet<TipoDePago> TipoDePagoes { get; set; }
        public virtual DbSet<TipoDeProveedor> TipoDeProveedors { get; set; }
        public virtual DbSet<TipoDeVenta> TipoDeVentas { get; set; }
        public virtual DbSet<TipoEmail> TipoEmails { get; set; }
        public virtual DbSet<UsuarioRecobrarCuenta> UsuarioRecobrarCuentas { get; set; }
        public virtual DbSet<Vehiculo> Vehiculoes { get; set; }
        public virtual DbSet<Vendedor> Vendedors { get; set; }
        public virtual DbSet<VentaEnvio> VentaEnvios { get; set; }
        public virtual DbSet<VentaProducto> VentaProductos { get; set; }
        public virtual DbSet<Venta> Ventas { get; set; }
    }
}
