//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALTiger
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vendedor()
        {
            this.CuentaVendedors = new HashSet<CuentaVendedor>();
        }
    
        public int ID { get; set; }
        public int PersonID { get; set; }
        public int DireccionID { get; set; }
        public int TelefonosID { get; set; }
        public Nullable<int> ECorreosID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public Nullable<System.DateTime> Changed { get; set; }
        public Nullable<int> ChangedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaVendedor> CuentaVendedors { get; set; }
        public virtual Direccion Direccion { get; set; }
        public virtual Email Email { get; set; }
        public virtual Person Person { get; set; }
        public virtual Telefono Telefono { get; set; }
    }
}
