//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALTiger
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentaEnvio
    {
        public int Id { get; set; }
        public Nullable<int> ProveedorEnviosID { get; set; }
        public Nullable<int> ClienteEntregaID { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public Nullable<System.DateTime> Changed { get; set; }
        public Nullable<int> ChangedBy { get; set; }
    }
}
