//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALTiger
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentaProducto
    {
        public int Id { get; set; }
        public Nullable<int> VentaId { get; set; }
        public Nullable<int> ProductoID { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> PrecioVenta { get; set; }
        public Nullable<bool> IncluirEnVenta { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public Nullable<System.DateTime> Changed { get; set; }
        public Nullable<int> ChangedBy { get; set; }
    }
}
